version: '3.4'
services:
  php:
    build: .
    container_name: php-xdebug-demo
    volumes:
      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./index.php:/var/www/html/index.php
    ports:
      - "8080:80"
    environment:
      XDEBUG_SESSION: 1
      PHP_IDE_CONFIG: serverName=xdebug
    extra_hosts:
      - "host.docker.internal:host-gateway"